//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增工作.
        /// </summary>
        internal static string AddJob {
            get {
                return ResourceManager.GetString("AddJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年齡.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 申請成為公司招募人.
        /// </summary>
        internal static string ApplyRecruiter {
            get {
                return ResourceManager.GetString("ApplyRecruiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回公司管理頁面.
        /// </summary>
        internal static string BackToCompanyMaster {
            get {
                return ResourceManager.GetString("BackToCompanyMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 變更密碼.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公司地址.
        /// </summary>
        internal static string CompanyAddress {
            get {
                return ResourceManager.GetString("CompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公司介紹.
        /// </summary>
        internal static string CompanyIntroduction {
            get {
                return ResourceManager.GetString("CompanyIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公司人數.
        /// </summary>
        internal static string CompanyMemberCount {
            get {
                return ResourceManager.GetString("CompanyMemberCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公司名稱.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公司電話.
        /// </summary>
        internal static string CompanyPhone {
            get {
                return ResourceManager.GetString("CompanyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公司資訊修改.
        /// </summary>
        internal static string CompanyProfileEdit {
            get {
                return ResourceManager.GetString("CompanyProfileEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找公司.
        /// </summary>
        internal static string CompanySearch {
            get {
                return ResourceManager.GetString("CompanySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成立年度.
        /// </summary>
        internal static string CompanyStartYear {
            get {
                return ResourceManager.GetString("CompanyStartYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公司網址.
        /// </summary>
        internal static string CompanyUrl {
            get {
                return ResourceManager.GetString("CompanyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確定.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認新密碼.
        /// </summary>
        internal static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認密碼.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加入時間.
        /// </summary>
        internal static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暱稱.
        /// </summary>
        internal static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編輯.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改公司資訊.
        /// </summary>
        internal static string EditCompany {
            get {
                return ResourceManager.GetString("EditCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電子信箱.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到網頁，請回到上一頁.
        /// </summary>
        internal static string Error404 {
            get {
                return ResourceManager.GetString("Error404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 發生不明錯誤，請回到上一頁.
        /// </summary>
        internal static string Error500 {
            get {
                return ResourceManager.GetString("Error500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回首頁.
        /// </summary>
        internal static string GoBackToHome {
            get {
                return ResourceManager.GetString("GoBackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入年齡.
        /// </summary>
        internal static string InputAge {
            get {
                return ResourceManager.GetString("InputAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入公司地址.
        /// </summary>
        internal static string InputCompanyAddress {
            get {
                return ResourceManager.GetString("InputCompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入公司介紹.
        /// </summary>
        internal static string InputCompanyIntroduction {
            get {
                return ResourceManager.GetString("InputCompanyIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入公司人數.
        /// </summary>
        internal static string InputCompanyMemberCount {
            get {
                return ResourceManager.GetString("InputCompanyMemberCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入公司名稱.
        /// </summary>
        internal static string InputCompanyName {
            get {
                return ResourceManager.GetString("InputCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入公司電話.
        /// </summary>
        internal static string InputCompanyPhone {
            get {
                return ResourceManager.GetString("InputCompanyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入公司成立年度.
        /// </summary>
        internal static string InputCompanyStartYear {
            get {
                return ResourceManager.GetString("InputCompanyStartYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入公司網址.
        /// </summary>
        internal static string InputCompanyUrl {
            get {
                return ResourceManager.GetString("InputCompanyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入暱稱.
        /// </summary>
        internal static string InputDisplay {
            get {
                return ResourceManager.GetString("InputDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入Email.
        /// </summary>
        internal static string InputEmail {
            get {
                return ResourceManager.GetString("InputEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入自我介紹.
        /// </summary>
        internal static string InputIntroduction {
            get {
                return ResourceManager.GetString("InputIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請選擇職缺地區.
        /// </summary>
        internal static string InputJobArea {
            get {
                return ResourceManager.GetString("InputJobArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入職缺說明.
        /// </summary>
        internal static string InputJobDetail {
            get {
                return ResourceManager.GetString("InputJobDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入該怎麼做.
        /// </summary>
        internal static string InputJobHow {
            get {
                return ResourceManager.GetString("InputJobHow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入職缺標題.
        /// </summary>
        internal static string InputJobTitle {
            get {
                return ResourceManager.GetString("InputJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請選擇職缺類型.
        /// </summary>
        internal static string InputJobType {
            get {
                return ResourceManager.GetString("InputJobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入該做什麼.
        /// </summary>
        internal static string InputJobWhat {
            get {
                return ResourceManager.GetString("InputJobWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入為什麼要做這個.
        /// </summary>
        internal static string InputJobWhy {
            get {
                return ResourceManager.GetString("InputJobWhy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入手機號碼.
        /// </summary>
        internal static string InputMobile {
            get {
                return ResourceManager.GetString("InputMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入姓名.
        /// </summary>
        internal static string InputName {
            get {
                return ResourceManager.GetString("InputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入您欲變更的密碼.
        /// </summary>
        internal static string InputNewPassword {
            get {
                return ResourceManager.GetString("InputNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請再次輸入您的新密碼.
        /// </summary>
        internal static string InputNewPasswordAgain {
            get {
                return ResourceManager.GetString("InputNewPasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入您的原始密碼.
        /// </summary>
        internal static string InputOldPassword {
            get {
                return ResourceManager.GetString("InputOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入密碼.
        /// </summary>
        internal static string InputPassword {
            get {
                return ResourceManager.GetString("InputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請再輸入一次密碼.
        /// </summary>
        internal static string InputPasswordAgain {
            get {
                return ResourceManager.GetString("InputPasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入最高薪資.
        /// </summary>
        internal static string InputSlaryEnd {
            get {
                return ResourceManager.GetString("InputSlaryEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入最低薪資.
        /// </summary>
        internal static string InputSlaryStart {
            get {
                return ResourceManager.GetString("InputSlaryStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請選擇職缺狀態.
        /// </summary>
        internal static string InputStatusType {
            get {
                return ResourceManager.GetString("InputStatusType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入標籤.
        /// </summary>
        internal static string InputTag {
            get {
                return ResourceManager.GetString("InputTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自我介紹.
        /// </summary>
        internal static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否結婚.
        /// </summary>
        internal static string IsMarried {
            get {
                return ResourceManager.GetString("IsMarried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 職缺地區.
        /// </summary>
        internal static string JobArea {
            get {
                return ResourceManager.GetString("JobArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刊登時間.
        /// </summary>
        internal static string JobCreateDate {
            get {
                return ResourceManager.GetString("JobCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 職缺說明.
        /// </summary>
        internal static string JobDetail {
            get {
                return ResourceManager.GetString("JobDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 職缺資訊修改.
        /// </summary>
        internal static string JobEdit {
            get {
                return ResourceManager.GetString("JobEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 該怎麼做.
        /// </summary>
        internal static string JobHow {
            get {
                return ResourceManager.GetString("JobHow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 職缺列表.
        /// </summary>
        internal static string JobList {
            get {
                return ResourceManager.GetString("JobList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找工作.
        /// </summary>
        internal static string JobSearch {
            get {
                return ResourceManager.GetString("JobSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 職缺標題.
        /// </summary>
        internal static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 職缺類型.
        /// </summary>
        internal static string JobType {
            get {
                return ResourceManager.GetString("JobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 該做什麼.
        /// </summary>
        internal static string JobWhat {
            get {
                return ResourceManager.GetString("JobWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 為什麼要做這個.
        /// </summary>
        internal static string JobWhy {
            get {
                return ResourceManager.GetString("JobWhy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關鍵字.
        /// </summary>
        internal static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 處理中....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登入.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登出.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已婚.
        /// </summary>
        internal static string Married {
            get {
                return ResourceManager.GetString("Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手機.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必填欄位.
        /// </summary>
        internal static string MustColumn {
            get {
                return ResourceManager.GetString("MustColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的公司.
        /// </summary>
        internal static string MyCompany {
            get {
                return ResourceManager.GetString("MyCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓名.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請注意，密碼變更完成後，您將需要立即以新密碼重新登入.
        /// </summary>
        internal static string NeedReLoginInfo {
            get {
                return ResourceManager.GetString("NeedReLoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最新.
        /// </summary>
        internal static string Newest {
            get {
                return ResourceManager.GetString("Newest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新密碼.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原密碼.
        /// </summary>
        internal static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選填欄位.
        /// </summary>
        internal static string OptionColumn {
            get {
                return ResourceManager.GetString("OptionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密碼.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的履歷.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 履歷修改.
        /// </summary>
        internal static string ProfileEdit {
            get {
                return ResourceManager.GetString("ProfileEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 推薦.
        /// </summary>
        internal static string Recommend {
            get {
                return ResourceManager.GetString("Recommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我要徵人.
        /// </summary>
        internal static string Recruitment {
            get {
                return ResourceManager.GetString("Recruitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 註冊新會員.
        /// </summary>
        internal static string RegisterNewUser {
            get {
                return ResourceManager.GetString("RegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 薪資範圍.
        /// </summary>
        internal static string SalaryRange {
            get {
                return ResourceManager.GetString("SalaryRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜尋.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜尋結果.
        /// </summary>
        internal static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 職缺狀態.
        /// </summary>
        internal static string StatusType {
            get {
                return ResourceManager.GetString("StatusType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 標籤.
        /// </summary>
        internal static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最後更新時間.
        /// </summary>
        internal static string UpdateDate {
            get {
                return ResourceManager.GetString("UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 會員登入.
        /// </summary>
        internal static string UserLogin {
            get {
                return ResourceManager.GetString("UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作部落格.
        /// </summary>
        internal static string WorkBlog {
            get {
                return ResourceManager.GetString("WorkBlog", resourceCulture);
            }
        }
    }
}
