namespace NiHonGo.Core.Enum
{
    public enum ErrorCode
    {
        EmailIsNull,
        PasswordIsNull,
        NameIsNull,
        UserNotFound,
        BlogNotFound,
        VideoNotFound,
        WordNotFound,
        OldPasswordIsNull,
        NewPasswordIsNull,
        EmailOrPasswordWrong,
        OldPasswordWrong,
        EmailFormatIsWrong,
        ChangePasswordFailed,
        AlreadyHadThisEmail,
        AlreadyHadThisVideo,
        AlreadyHadThisWord,
        NoAuthentication,
        YoutubeUrlIsNull,
        JapaneseTitleIsNull,
        JapaneseContentIsNull,
        ChineseTitleIsNull,
        ChineseContentIsNull,
        BlogTitleIsNull,
        BlogDetailIsNull,
        InternalError,
    }
}
